version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/captaacao-api
    restart: always
    command: bash -c "npm install -g tsc && npm install --only=prod && npm run build && npm run start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/captaacao-api
    volumes:
      - .:/usr/src/captaacao-api/
      - ./node_modules:/usr/src/captaacao-api/node_modules
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo

