version: "3"
services:
  mongo:
    container_name: mongo-container_name
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: survey-pet-api
    restart: always
    command: npm debug
    environment:
      - MONGO_URL=mongodb://mongo:27017/survey-pet-api
    volumes:
      - ./dist:/usr/src/survey-pet-api/dist
      - ./package.json:/usr/src/survey-pet-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo

